version: '3'
services:
  php-fpm:
    container_name: php
    build: ./docker/php-fpm
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html

  nginx:
    container_name: nginx
    image: nginx:stable
    ports:
      - 85:80
    links:
      - php-fpm
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf

  postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: cqrs